name: navigator_apps
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^6.5.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
    

flutter:
  uses-material-design: true
  assets:
  - assets/barbie.jpg
  - assets/fast.jpg
  - assets/lisa.jpg